### ISSUE TITLE
Mermaid as code

### ISSUE THREAD

**Issue by larssonper** [Seao/grav-plugin-diagrams#6]
Would it be possible to also render mermaid syntax that is in a code-block, ` ```mermaid` as an alternative to `[mermaid]` tags?

Eg.

<pre>
```mermaid
sequenceDiagram
    Alice->>John: Hello John, how are you?
    John-->>Alice: Great!
```
</pre>

Thanks.

**Comment by Seao** [comment]
Hi @larssonper,

This code-block syntax was my original ambition when I created this plugin, because I was inspired by stackedit.io which is using it. However I faced up several problems during the implementation : the regular expression to catch the code-block was in conflict during the page creation process with the markdown render, which was adding unnecessary tags that influenced the generated diagrams. It was easier to switch to tags, which doesn't alter the render, and it's not in my plan to come back on this design choice.
